### ISSUE TITLE
discussion search

### ISSUE THREAD

**Issue by levelos** [thinkshout/mandrill_groups#2]
Currently searching comments but not discussion title. Can we do both?!

**Comment by nrackleff** [comment]
This is fixed in this commit in the givingforum repo mandrill_groups branch. https://github.com/thinkshout/givingforum/commit/fef00dabd2eb2ca374f4ba6a3e02909cc4c583ab 
Updated the gf_discussion_groups feature view to change the exposed comment filter to a combined filter to search both discussion titles as well as comments.
